enum actions {
    GET_REQUEST = "GET_REQUEST",
    GET_SUCCESS = "GET_SUCCESS",
    GET_FAIL = "GET_FAIL",

    ADD_REQUEST = "ADD_REQUEST",
    ADD_SUCCESS = "ADD_SUCCESS",

    REMOVE_REQUEST = "REMOVE_REQUEST",
    REMOVE_SUCCESS = "REMOVE_SUCCESS",

    UPDATE_REQUEST = "UPDATE_REQUEST",
}

export default actions;

